# Generated by Django 4.1.3 on 2022-11-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_price_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='attributes',
            new_name='path',
        ),
    ]
