# Generated by Django 4.1.3 on 2022-11-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_attributes_website_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], default='hours', max_length=24),
            preserve_default=False,
        ),
    ]
